# Generated by Django 5.2.13 on 2026-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(help_text='1-2 line preview shown on project cards', max_length=200)),
                ('full_description', models.TextField()),
                ('category', models.CharField(choices=[('AI Agent', 'AI Agent'), ('Automation', 'Automation'), ('Active Agent', 'Active Agent'), ('Other', 'Other')], default='AI Agent', max_length=32)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Live', 'Live'), ('Planned', 'Planned')], default='Planned', max_length=16)),
                ('image', models.ImageField(blank=True, help_text='Optional cover image shown on the card and detail page', null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
