# Generated by Django 5.2.13 on 2026-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Boomi AI Agents', 'Boomi AI Agents'), ('Boomi Agents', 'Boomi Agents'), ('Active Agent', 'Active Agent'), ('Other', 'Other')], default='Boomi AI Agents', max_length=32),
        ),
    ]
