# Generated by Django 5.2.13 on 2026-05-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_category_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Boomi AI Agents', 'Boomi AI Agents'), ('Hathority In-House Agents', 'Hathority In-House Agents'), ('Active Engagements', 'Active Engagements'), ('Other', 'Other')], default='Boomi AI Agents', max_length=32),
        ),
    ]
