# Generated by Django 5.2.13 on 2026-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Optional demo video shown on the detail page (mp4 recommended)', null=True, upload_to='project_videos/'),
        ),
    ]
