# Generated by Django 5.2.13 on 2026-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text="OneDrive share link — paste the 'Anyone with the link can view' URL here", null=True),
        ),
    ]
