# Generated by Django 5.2.13 on 2026-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='built_by',
            field=models.CharField(blank=True, help_text='Name of the person or team who built this agent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated_on',
            field=models.DateField(blank=True, help_text='Date this agent was last updated', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='published_on',
            field=models.DateField(blank=True, help_text='Date this agent was published', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_type',
            field=models.CharField(blank=True, choices=[('Automation', 'Automation'), ('Integration', 'Integration'), ('AI Agent', 'AI Agent'), ('Workflow', 'Workflow'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a Google Drive or OneDrive share link here', null=True),
        ),
    ]
