# Generated by Django 5.2.13 on 2026-05-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_built_by_project_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='solution_type',
            field=models.CharField(blank=True, choices=[('Accelerator', 'Accelerator'), ('Agents', 'Agents'), ('AI Agent Accelerator', 'AI Agent Accelerator'), ('AI Agent Recipe', 'AI Agent Recipe'), ('Designer Agent Accelerator', 'Designer Agent Accelerator'), ('Designer Agent Recipe', 'Designer Agent Recipe'), ('Recipe', 'Recipe'), ('Task Automation', 'Task Automation')], max_length=30, null=True),
        ),
    ]
