# Generated by Django 5.2.13 on 2026-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_solution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text="One feature per line in format 'Title : Description'. Each line becomes a bullet point.", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='built_by',
            field=models.CharField(default='HATHORITY | Partner', help_text='Name of the person or team who built this agent', max_length=100),
        ),
    ]
