# Generated by Django 5.2.13 on 2026-05-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_key_features_alter_project_built_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_updated_on',
        ),
    ]
