# Generated by Django 5.2.13 on 2026-05-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_last_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='difficulty',
        ),
    ]
