# Generated by Django 5.2.14 on 2026-05-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
