# Generated by Django 5.2.14 on 2026-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_url',
            field=models.URLField(blank=True, help_text='Official public link for this agent (e.g. Boomi listing page)', null=True),
        ),
    ]
